name: 11 - Workflow with inputs
on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip deployment and only print build output
                default:  false
            target:
                type: environment
                description: Whicht environment the workflow should target
            tag:
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
                description: Release from which to build and deploy    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: | 
        echo "Building from Tag: ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    steps:
      - name: Deploy
        run: | 
          echo "Deploying to: ${{ inputs.target }}"