name: 12 - Working with Outputs

on: 
  workflow_dispatch:
    inputs: 
      build-status: 
        type: choice
        options: 
          - success
          - failure
        description: 'Build status'
        required: true
        default: success
jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT" 
      - name: Build
        id: build
        run: |
          echo "$GITHUB_OUTPUT" 
          echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"