name: 13 - using caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "Wethere to execute cache"
        required: true
        default: true
      node-version:
        type: choice
        options:
          - "18.x"
          - "20.x"
          - "21.x"
          - "22.x"
        description: "Node version to use"
        required: true
        default: "22.x"

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching
    outputs:
      cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Calculate cache key
        id: cache-key
        run: echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/package-lock.json') }}" >> "$GITHUB_OUTPUT"

      - name: Download cache dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache-dependencies
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: 13-caching/node_modules
          
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check the cache content
        run: ls -la ~/.npm
  lint-test-build:
    runs-on: ubuntu-latest
    needs: install-deps

    defaults:
      run:
        working-directory: 13-caching
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache-dependencies
        with:
          key: ${{ needs.install-deps.outputs.cache-key }}
          path: 13-caching/node_modules

      - name: Unit Testing
        run: npm test
      - name: Linting
        run: echo "Linting the code"

  build:
    runs-on: ubuntu-latest
    needs: install-deps

    defaults:
      run:
        working-directory: 13-caching
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
      - name: Download dependencies
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache-dependencies
        with:
          key: ${{ needs.install-deps.outputs.cache-key }}
          path: 13-caching/node_modules

      - name: Unit Testing
        run: npm test
      - name: Building the code
        run: npm run build
      - name: Deploy to nonprod
        run: echo "Deploying the code to nonprod"
