name: 13 - using caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        description: "Wethere to execute cache"
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Unit testing
        run: npm test
      - name: Building the code
        run: npm run build
      - name: Deploy to nonprod
        run: echo "Deploying the code to nonprod"
